config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'schedules#index', as: 'home'

  resources :workorders
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
	belongs_to :workOrder, foreign_key: 'location_id'
end

app/models/technician.rb
class Technician < ApplicationRecord
	has_many :workOrders, foreign_key: 'technician_id', primary_key: 'id'

	def get_work
		workOrders.joins(:location).select("work_orders.*, locations.*").as_json
	end
end

app/models/work_order.rb
class WorkOrder < ApplicationRecord
	has_one :location, foreign_key: 'id', primary_key: 'location_id'
	belongs_to :technician, primary_key: 'id', foreign_key: 'technician_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
	def index
		require 'date'
		
		@technicians = Technician.all.as_json

		@technicians.each do |t|
			t["work"] = Technician.find_by_id(t["id"]).get_work
		end



	end
end

app/controllers/workorders_controller.rb
class WorkordersController < ApplicationController
	def new
		@workorder = WorkOrder.new
	end
	def show
		@workorder = WorkOrder.find(params[:id])
	end
	def create

		@workorder = WorkOrder.new #(work_params)
		if @workorder.save
			redirect_to root_path
		else
			flash.now[:alert] = @workorder.errors.full_messages
		end
	end
	private 
=begin
	def work_params
		params.require(:technician_id, :location_id, :time, :duration, :price) #.permit(:technician_id, :location_id, :time, :duration, :price)
	end
=end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RottlerSchedulingApp2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <div class="container">
      <%= yield %>
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
    <%= javascript_include_tag 'schedules' %>

  </body>
</html>

app/views/schedules/index.html.erb
<% start = Time.new(2019,10,01, 0, 00, 00).to_time.utc.to_i %>
<% stop  = Time.new(2019,10,01, 15, 00, 00).to_time.utc.to_i %>

<h1>Schedule</h1>
<div class="row">

	<div class="col-1 time" style="padding:0px;">
		<div><h4>&nbsp;</h4></div>
		<%# creates left time scale in 1 hour increments %>
		<% (start..stop).step(1.hour).each do |ts| %>
			<div class="hour-box">
				<div class="deets">
					<%= Time.at(ts).utc.strftime('%l:%M%p') %>
				</div>
			</div>
		<% end %>
	</div>
	<div class="col-11" style="padding:0px;">
		<div class="row" id="schedule">
			<% @technicians.each do |t| %>
				
				<div id="<%= t["id"] %>" class="col tech-col" style="padding:0px;">
					<h4 class="text-center tech-name"><%= t["name"] %></h4>
					<% arr = [] %>
					<% t["work"].each{|v| arr.push(v["time"]) } %>
					
					<% overlap = 0 %> <%# time in minutes that the work exceeds the one hour incrementation %>
					<% endTime = nil %>
					<% prevEndTime = nil %>
					<% (start..stop).step(1.hour).each do |ts| %>
						
						<% ct = Time.at(ts).utc %>
						<% scheduled = false %>
							<% if overlap < 60 || arr.any?{|time| (time.to_time.utc).to_i.between?(ct.to_i, (ct + 60*60-overlap).to_i)} %> <%# skips generating box if work duration covers the hour increment %>
								<% t["work"].each do |w| %>
									<% realTime = w["time"].to_time.utc %>
									<%# if the work order time falls within the hour incrementation %>

									<% if (realTime).to_i >= ct.to_i && (realTime).to_i < (ct+60*60-overlap).to_i %> 
										<% scheduled = true %>
										<% endTime = realTime+60*(w["duration"].to_i) %>

										<%# if workorder start time is on the hour eg 4:00 %>
										<% if (realTime) == ct %>
											
											<% overlap = w["duration"] - 60  %>
											<%# creates a box showing scheduled work, location, start and end times %>
											<div class="hour-box scheduled text-center" style="height:<%= (w["duration"]*2) %>px;" data-city="<%= w["city"] %>" data-price="<%= w["price"] %>" data-duration="<%= w["duration"] %>" data-start="<%= (realTime).strftime('%l:%M%p') %>" data-end="<%= (realTime+60*(w["duration"].to_i)).strftime('%l:%M%p') %>">
												<div class="deets">
													<p class="name"><%= w["name"] %></p>
													<p><%= w["city"] %></p>
													<p><%= "$#{w["price"]}" %></p>
													<p class="sched-time"><%= "#{(realTime).strftime('%l:%M%p')} to #{(realTime+60*(w["duration"].to_i)).strftime('%l:%M%p')}" %></p>
												</div>
											</div>
										<%# if work order start time occurs at some point not on the hour eg 4:15 %>
										<% else %>






											<% offset = ((realTime) - ct) / 60 %> <%# time in minutes from the start of the hour %>
											<% overlap = (w["duration"] + offset) - 60  %>
											<% if prevEndTime.blank? || prevEndTime.to_i <= ct.to_i %>
												<%# creates a "nothing scheduled" box for the time from the start of the hour to the start of the work %>
												<div class="hour-box text-center" data-overlap="<%= overlap %>" style="height:<%= (offset*2) %>px;" data-start="<%= ct.strftime('%l:%M%p') %>" data-end="<%= (ct+offset*60).strftime('%l:%M%p') %>">
													<div class="deets">
														<p>Nothing Scheduled</p>
														<p class="sched-time">(<%= "#{ct.strftime('%l:%M%p')} - #{(ct+offset*60).strftime('%l:%M%p')}" %> )</p>
													</div>
												</div>
											<% end %>
											<%# creates a box showing scheduled work, location, start and end times %>
											



											<div class="hour-box scheduled text-center" style="height:<%= (w["duration"]*2) %>px;" data-city="<%= w["city"] %>" data-price="<%= w["price"] %>" data-duration="<%= w["duration"] %>" data-start="<%= (realTime).strftime('%l:%M%p') %>" data-end="<%= (realTime+60*(w["duration"].to_i)).strftime('%l:%M%p') %>">
												<div class="deets">
													<p class="name"><%= w["name"] %></p>
													<p><%= w["city"] %></p>
													<p><%= "$#{w["price"]}" %></p>
													<p class="sched-time"><%= "#{(realTime).strftime('%l:%M%p')} to #{(realTime+60*(w["duration"].to_i)).strftime('%l:%M%p')}" %></p>
												</div>
											</div>

										<% end %>
										<% prevEndTime = realTime+60*(w["duration"].to_i) %>
									<% end %>							
								<% end %>
							
								<% if !scheduled %>
									<%# nothing was scheduled for this hour incrementation, creates a "nothing scheduled" box %>
									<div class="hour-box text-center" data-overlap="<%= overlap %>" style="height:<%= 120-(overlap*2) %>px;" data-start="<%= (endTime.blank? ? ct+overlap*60 : endTime).strftime('%l:%M%p') %>" data-end="<%= (ct+60*60).strftime('%l:%M%p') %>">
										<div class="deets">
											<p>Nothing Scheduled</p>
											<p class="sched-time">(<%= "#{(endTime.blank? ? ct+overlap*60 : endTime).strftime('%l:%M%p')} - #{(ct+60*60).strftime('%l:%M%p')}" %> )</p>
										</div>
									</div>
									<% overlap = 0 %>
									<% endTime = nil %>
									<% prevEndTime = nil %>
								<% end %>
							<% else %>
								<% overlap = overlap - 60 %>
							<% end %>


						
					<% end %>
				</div>

			<% end %>
		</div>
	</div>
</div>

<%# modal showing work order details or time between work on click. js for click in /assets/javascripts/schedules.js %>
<div class="modal fade" id="schedule_deets" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<input type="hidden" id="technician_id" value="">
				<h5 class="modal-title"><span class="start-time"></span> - <span class="end-time"></span></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
			<div class="modal-body">
				<p>Technician: <span class="name"></span></p>
				<div class="not-scheduled" style="display:none;">
					<p><span class="name"></span> is available between <span class="last"></span> and <span class="next"></span></p>
				</div>
				<div class="scheduled" style="display:none;">
					<p><span class="name"></span> is working at <span class="jobsite"></span> in <span class="city"></span> between <span class="start-time"></span> and <span class="end-time"></span></p>
					<p>Price: <span class="price"></span></p>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary schedule-new" data-target="#schedule_new" data-toggle="modal">Schedule Job</button>
        		<button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="schedule_new" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title">Schedule new job for <span class="name"></span></h5>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			</div>
			<div class="modal-body">
				<%= form_for :workorders, url: workorders_path do |f| %>
					<% flash.each do |type, msg| %>
						<div class="alert alert-danger">
							<%= msg %>
						</div>
					<% end %>
					<%= f.text_field(:technician_id, {type: 'hidden'}) %>
					<p>
						<%= f.label :location_id %><br>
						<%= f.collection_select :location_id, Location.order(:name),:id,:name, {prompt: "Select a location"}, {class: "form-control"} %>
					</p>
					<p>
						<%= f.label :time %><br>
						<%= f.text_field(:time, {class: 'form-control'}) %>
					</p>
					<p>
						<%= f.label :duration %><br>
						<%= f.text_field(:duration, {class: 'form-control'}) %>
					</p>
					<p>
						<%= f.label :price %><br>
						<%= f.text_field(:price, {class: 'form-control'}) %>
					</p>
					<p>
						<%= f.submit({class: 'btn btn-primary'}) %>
					</p>

				<% end %>
			</div>
		</div>
	</div>
</div>